# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Phoenix-Chat-Starter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Phoenix-Chat-Starter
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Firestore'
    pod 'ChameleonFramework'

  target 'Phoenix-Chat-StarterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Phoenix-Chat-StarterUITests' do
    # Pods for testing
  end

end
